#   ******************************************************************
#      Copyright (c) 1999   Smithsonian  Astrophysical  Observatory
#   The contents of this file are protected under the copyright notice
#   contained in the file  COPYRIGHT_SAO located in the root directory
#   of this distribution.
#   ******************************************************************

# Makefile for whole pimms directory
#

MK_TOP = ../../../../..

include $(MK_TOP)/infra/Makefile.prop


SCRIPTS		= prop_pimms

include $(MK_TOP)/infra/Makefile.all



# pimms.ps:	pimms.tex
	# $(LATEX) pimms.tex
	# $(DVIPS) -o $@ pimms.dvi
