# Makefile for obs/ui/vv (User Interface for V&V) 
#
MK_TOP  = ../../..
include $(MK_TOP)/infra/Makefile.master

MODULES = htdocs
WEBINSTALL_MODULES = htdocs

include $(MK_TOP)/infra/Makefile.module

# DO NOT DELETE THIS LINE -- make depend depends on it.
