#
#
MK_TOP  = ../../../../../../
include $(MK_TOP)/include/Makefile.cxc


DATA_DIR = $(PR_TOP)/PeerReviewGUI/lib/Tk

DATA_FILES = \
	EnumList.pm \
	ViewTable.pm

include $(MK_TOP)/Makefile.all
COPY_P 	= cp -f

# DO NOT DELETE THIS LINE -- make depend depends on it.
