# Makefile for whole prop directory.

MK_TOP = ../..
MODULES = doc receiver reports panel prop_viewer tools gov webapps 
WEBINSTALL_MODULES = prop_viewer gov 


include $(MK_TOP)/infra/Makefile.module
