#
# Peer Review GUI SQL scripts for CDO 
#
MK_TOP  = ../../../../../
include $(MK_TOP)/infra/Makefile.cxc

DATA_DIR = $(PR_TOP)/PeerReviewCDO/SQL

DATA_FILES = \
	README \
	basic_status_all_panels.sql \
	panel_progress.sql \
	target_list.sql \
	find_locked.sql \
	joint_list.sql \
	archive_list.sql \
	theory_list.sql \
	multicycle_list.sql \
	bpp_list.sql \
	alt_target_list.sql \
	monitor.sql \
	raster.sql 

include $(MK_TOP)/infra/Makefile.all
COPY_P 	= cp -f

# DO NOT DELETE THIS LINE -- make depend depends on it.
