#
#
MK_TOP  = ../../../../../
include $(MK_TOP)/infra/Makefile.cxc

MODULES = Tk

include $(MK_TOP)/infra/Makefile.module       # Makefile for whole directory tree

DATA_DIR = $(PR_TOP)/PeerReviewGUI/lib

DATA_FILES = \
	AltGrp.pm \
	BuildSort.pm \
	BuildTable.pm \
	BuildView.pm \
	BVNotebook.pm \
	BVPage.pm \
	config.pm \
	EditNotebook.pm \
	EditPage.pm \
	MkGroup.pm \
	Monitor.pm \
	Panel.pm \
	Print.pm \
	PrintPreview.pm \
	ProposalList.pm \
	Proposal.pm \
	Resurrect.pm \
	Target.pm \
	Too.pm

include $(MK_TOP)/infra/Makefile.all
COPY_P 	= cp -f

# DO NOT DELETE THIS LINE -- make depend depends on it.
