	  <h3>Table of Contents</h3>
	  <div id="accordian">
	    <h2><a href="#">Overview</a></h2>
	    <div class="nav" id="overview">
              <ul>
                <li><a href="index.shtml">Overview</a></li>
              </ul>
	    </div>
	    <h2><a href="#">File Menu</a></h2>
	    <div class="nav" id="file_menu">
	      <ul>
                <li><a href="FileMenu.shtml">File Menu</a>
                <ul>
		  <li class="navlist">Print Panel View</li>
		  <li class="navlist">Ascii Dump of Comments</li>
		  <li class="navlist">Ascii Dump of Panel View</li>
		  <li class="navlist">Ascii Dump of Allotments </li>
		  <li class="navlist">Ascii Dump of Conflicts </li>
		  <li class="navlist">Quit</li>
                </ul>
	        </li>
	      </ul>
	    </div>
	    
	    <h2><a href="#">Tools</a></h2>
	    <div class="nav" id="tools">
	      <ul>
                <li><a href="Tools.shtml">Tools</a>
                <ul>
		  <li class="navlist">Assign Groups</li>
		  <li class="navlist">Resurrect Proposal</li>
		  <li class="navlist">Triage</li>
		  <li class="navlist">Hide/Unhide Triaged Proposals</li>
		  <li class="navlist">Hide/Unhide Archive/Theory Proposals</li>
		  <li class="navlist">Hide/Unhide LP/VLP Proposals</li>
		  <li class="navlist">Build View</li>
		  <li class="navlist">Build Sort</li>
                </ul>
	        </li>
	      </ul>
	    </div>

	    <h2><a href="#">Finalize Menu</a></h2>
	    <div class="nav" id="finalize">
              <ul>
                <li><a href="Finalize.shtml">Finalize Menu</a>
	        <ul>
		  <li class="navlist">Finalize Time Allocation</li>
		  <li class="navlist">Back to Facilitator View</li>
		  <li class="navlist">Reset Rank</li>
		  <li class="navlist">Print Finalize View</li>
                </ul>
	        </li>
	      </ul>
	    </div>

	    <h2><a href="#">Views</a></h2>
	    <div class="nav" id="view">
              <ul>
                <li><a href="View.shtml">Panel View</a></li>
              </ul>
	    </div>
	    
	    <h2><a href="#">Sorts</a></h2>
	    <div class="nav" id="sort">
              <ul>
                <li><a href="Sort.shtml">Panel Sort </a></li>
              </ul>
	    </div>
	    
	    
	    <h2><a href="#">Panel Zoom</a></h2>
	    <div class="nav" id="zoom">
	      <ul>
                <li><a href="Zoom.shtml">Panel Zoom</a></li>
	      </ul>
	    </div>

	    <h2><a href="#">Proposal Edit Notebook</a></h2>
	    <div class="nav" id="prop_edit">
              <ul>
                <li><a href="ProposalEdit.shtml">Proposal Edit Notebook</a></li>
              </ul>
	    </div>
	    
	    <h2><a href="#">Column Definitions</a></h2>
	    <div class="nav" id="col_defs">
              <ul>
                <li><a href="ColDef.shtml">Column Definitions</a></li>
              </ul>
	    </div>
	    
	    <h2><a href="#">Miscellaneous Things</a></h2>
	    <div class="nav" id="misc">
              <ul>
                <li><a href="Misc.shtml">Miscellaneous Things</a>
	        <ul>
		  <li class="navlist">Searching Within a View</li>
		  <li class="navlist">Status Page</li>
		  <li class="navlist">Editing Proposals</li>
	        </ul>
	        </li>
	      </ul>
	    </div>
	    
	    <h2><a href="#">FAQ</a></h2>
	    <div class="nav" id="faq">
	      <ul>
                <li><a href="FAQ.shtml">Frequently Asked Questions</a>
	        <ul>
		  <li class="navlist">Entering Zero Grade</li>
		  <li class="navlist">Where's the Search String?</li>
		  <li class="navlist">Positive Balance Is Red</li>
		  <li class="navlist">Can't Edit Field that Panel Wants to Change</li>
		  <li class="navlist">Money in Time Field</li>
		  <li class="navlist">New group not appearing in proposal edit page</li>
	          <li class="navlist">Triage column values</li>
	          <li class="navlist">Proposals not appearing in Resurrect page</li>
	        </ul>
	        </li>
               </ul>
	    </div>
	  </div>
	  <p>Return to 
          <a href="https://cxc.cfa.harvard.edu/rws/facilitator_info.php">Facilitator Information Page</a></p>
