	  <h3>Symbol Key</h3>
	  <ul>
	    <li><span class="menu_item">Menu Item</span> is a menu item from a pull down menu in the tool bar.
	    <li><span class="button">Button</span> is a button located in a window.</li>
	    <li><span class="checkbox"><span class="box">&#9633;</span> Checkbox</span> is a checkbox located in a window.</li>
	      <li><span class="column">Column Name</span> is the heading of a column in a table.</li>
	  </ul>
