#
#
MK_TOP  = ../../../../
include $(MK_TOP)/infra/Makefile.cxc

MODULES = docs lib bin

include $(MK_TOP)/infra/Makefile.module       # Makefile for whole directory tree


include $(MK_TOP)/infra/Makefile.all
COPY_P 	= cp -f

# DO NOT DELETE THIS LINE -- make depend depends on it.
