#   ******************************************************************
#      Copyright (c) 1999   Smithsonian  Astrophysical  Observatory
#   The contents of this file are protected under the copyright notice
#   contained in the file  COPYRIGHT_SAO located in the root directory
#   of this distribution.
#   ******************************************************************

# Makefile for whole pimms directory
#

MK_TOP = ../../../..


MODULES = source models data scripts

include $(MK_TOP)/infra/Makefile.module	# Makefile for whole directory tree

