# Makefile for the Java packages in sao.
#

MK_TOP = ../../../..
PROP_DIR = ../..

MODULES = asc
WEBINSTALL_MODULES = $(MODULES)

include $(MK_TOP)/infra/Makefile.module	# Makefile for whole directory tree
