#
#
MK_TOP  = ../../../
include $(MK_TOP)/infra/Makefile.cxc

MODULES = PeerReviewDB PeerReviewCDO PeerReviewGUI GuiHelp GUI2Proposal 

include $(MK_TOP)/infra/Makefile.module       # Makefile for whole directory tree

COPY_P 	= cp -f

# DO NOT DELETE THIS LINE -- make depend depends on it.
