# _INSERT_SAO_COPYRIGHT_HERE_(2008)_
# _INSERT_GPL_LICENSE_HERE_



MK_TOP  = 	../../../..
include 	$(MK_TOP)/infra/Makefile.cxc   # Sets ASCDS_ env. variables


DATA_FILES = provis_config.cgi \
	provis.ephemeris.dat \
	horizhatchdashed.xbm \
	horizhatchdotted.xbm \
	horizhatchsolid.xbm \
	lefthatchdashed.xbm \
	lefthatchdotted.xbm \
	lefthatchsolid.xbm \
	righthatchdashed.xbm \
	righthatchdotted.xbm \
	righthatchsolid.xbm \
	verthatchdashed.xbm \
	verthatchdotted.xbm \
	verthatchsolid.xbm


include	$(MK_TOP)/infra/Makefile.all
