ROOT_DIR = ../../../..

TARGET_DIR = $(ROOT_DIR)/classes/gov/sao/asc/util

JAVAFILES = ComboBox.java \
	ComboBoxBorderPanel.java \
	ComboBoxModel.java \
	ComponentUtil.java \
	Frame.java \
	GridBagLayoutUtil.java \
	LogClient.java \
	Pair.java \
	PasswordField.java \
	Profiler.java \
	ToggleLookAndFeel.java \
	XML.java

include $(ROOT_DIR)/GNUmakefile.inc
