ROOT_DIR = ../../../..

TARGET_DIR = $(ROOT_DIR)/classes/gov/sao/asc/event

JAVAFILES = AddInterface.java \
	AddListener.java \
	CancelButtonListener.java \
	CancelInterface.java \
	CheckBoxInterface.java \
	CheckBoxListener.java \
	ComboBoxInterface.java \
	ComboBoxListener.java \
	DeleteInterface.java \
	DeleteListener.java \
	OKButtonListener.java \
	OKInterface.java \
	TextAreaInterface.java \
	TextAreaListener.java \
	TextFieldInterface.java \
	TextFieldListener.java \
	WindowInterface.java \
	WindowListener.java

include $(ROOT_DIR)/GNUmakefile.inc
