#
#
MK_TOP  = ../../../../../
include $(MK_TOP)/infra/Makefile.cxc


DATA_DIR = $(PR_TOP)/PeerReviewDB/data/

DATA_FILES = \
	gui_columns.dat \
	gui_sorts.dat \
	gui_table_columns.dat \
	gui_views.dat

include $(MK_TOP)/infra/Makefile.all
COPY_P 	= cp -f

# DO NOT DELETE THIS LINE -- make depend depends on it.
