#
#
MK_TOP  = ../../../../
include $(MK_TOP)/infra/Makefile.cxc


DATA_DIR = $(PR_TOP)/GUI2Proposal

DATA_FILES = \
	migrate_tables.pl 


include $(MK_TOP)/infra/Makefile.all
COPY_P 	= cp -f

# DO NOT DELETE THIS LINE -- make depend depends on it.
