# Makefile for proposal tools.

MK_TOP = ../../..

#Note: waves dir is not included in build (helpful code, not required)
#205a: rm nutils; add jcmutils jcmio unitlib ;
MODULES = jcm_misc jcm_libdata jcmutils jcmio jcmcal unitlib jcmastro \
	  calconv precesslib jcmfits dates precess nhlib colden \
	  pimms pileup eadata doc

include $(MK_TOP)/infra/Makefile.module

