#
#
MK_TOP  = ../../../../..
include $(MK_TOP)/infra/Makefile.cxc


DATA_DIR = $(PR_TOP)/PeerReviewGUI/docs

DATA_FILES = \
	docs.src \
	PR_docs.tex

include $(MK_TOP)/infra/Makefile.all
COPY_P 	= cp -f

# DO NOT DELETE THIS LINE -- make depend depends on it.
