# _INSERT_SAO_COPYRIGHT_HERE_(2008)_
# _INSERT_GPL_LICENSE_HERE_
#-----------------------------------------------------------------------
#
#               Makefile for the Provis tool
#
#-----------------------------------------------------------------------
MK_TOP = ../../..


# Define local include and library directories

MODULES = app data htdocs cgi-bin
WEBINSTALL_MODULES = htdocs cgi-bin app


include $(MK_TOP)/infra/Makefile.module



# DO NOT DELETE THIS LINE -- make depend depends on it.


