# Makefile for whole ui directory.
#

MK_TOP = ../..
include $(MK_TOP)/infra/Makefile.cxc


MODULES =  cxc_include prop op provis obsvis_web propsearch scripts cps
WEBINSTALL_MODULES = cxc_include op provis obsvis_web propsearch cps

include $(MK_TOP)/infra/Makefile.module


# DO NOT DELETE THIS LINE -- make depend depends on it.
