#!/bin/sh
#_SH_INSERT_SAO_COPYRIGHT_HERE_(1997-2008,2012)_
#_SH_INSERT_GPL_LICENSE_HERE_

if [ "$ASCDS_PROP_DATE_DATA" = "" ]
then
    #11/8/2012:   echo "ASCDS_PROP_DATE_DATA is not set;"
    ASCDS_PROP_DATE_DATA="$ASCDS_INSTALL/config/jcm_data"
    #11/8/2012:   echo "  default assignment to $ASCDS_INSTALL/config/jcm_data has been made."
fi

JCMPATH=$ASCDS_PROP_DATE_DATA
export JCMPATH

#11/8/2012:   echo "ASCDS_PROP_DATE_DATA (becomes JCMPATH, for time zones) ="
#11/8/2012:   echo "  $ASCDS_PROP_DATE_DATA"

prop_dates_exe $*
